chukong/cocos-docs

- manual/framework/native/v3/physics-integration/ja.md
> Physicsの統合について翻訳

- manual/framework/native/v2/gui/container/ja.md
cocos-docs/manual/framework/native/v2/gui/containerの翻訳
> Container Layerの翻訳

- manual/framework/native/v3/data-structure/vector/ja.md
manual/framework/native/v3/data-structure/vectorにja.mdを追加しました
> Vectorについての翻訳

- manual/framework/cocos2d-js/2-working-environment-and-workflow/2-1-cocos2d-js-lite-workflow/ja.md
manual/framework/cocos2d-js/2-working-environment-and-workflow/2-1-cocos2d-js-lite-workflow
の日本語ページを追加しました。
> Add cocos2d-js/2-working-environment-and-workflow/2-1-cocos2d-js-lite-workflow/ja.md

- manual/studio/v2/chapter5/connect-solution/en.md
- manual/studio/v2/chapter5/debug-on-browser/en.md
- manual/studio/v2/chapter5/introduceCocos/en.md
- manual/studio/v2/chapter5/load-export-datafile/en.md
- manual/studio/v3/chapter5/debug-on-browser/zh.md
- manual/studio/v3/chapter5/introduceCocos/zh.md
> Fixed Chinese/English course

- manual/studio/v2/chapter5/introduceCocos/en.md
> Fixed introduceCocos/en.md

- manual/studio/v2/chapter5/load-export-datafile/en.md
- manual/studio/v3/chapter5/load-export-datafile/zh.md
Fixed load-export-datafile/en.md
Fixed load-export-datafile/zh.md
> Fixed load-export-datafile

- manual/code-ide/install-idea-zh.md
> fix ide doc bug

- manual/studio/v2/chapter5/introduceCocos/en.md
fixed the title of introduceCocos/en.md
> fixed the title of introduceCocos/en.md

- manual/code-ide/install-idea-zh.md
> update ide doc

- manual/framework/html5/v3/cc-actions/ja.md
manual/framework/html5/v3/cc-actionsの日本語ページを作成しました。( 修正済 )
> Add manual/framework/html5/v3/cc-actions/ja

- manual/studio/v4/chapter4/Directory/en.md
> Add the English of faq

- manual/studio/v4/chapter4/Directory/en.md
Fixed v4/chapter4/Directory/en.md
> Fixed v4/chapter4/Directory/en.md

- manual/framework/html5/v3/reflection/ja.md
manual/framework/html5/v3/reflectionの日本語ページを追加しました。
> Add manual/framework/html5/v3/reflection/ja

- manual/framework/cocos2d-js/catalog/index.html
> modify url

- manual/studio/v4/chapter1/Support/en.md
- manual/studio/v4/chapter1/Support/tw.md
- manual/studio/v4/chapter1/Support/zh.md
> forum website update

- manual/studio/v4/chapter3/Extend/CustomExport/en.md
- manual/studio/v4/chapter3/Extend/CustomExport/tw.md
- manual/studio/v4/chapter3/Extend/CustomExport/zh.md
update custom export interface content for Cocos version 2.3.3
> update content in it for Cocos version 2.3.3.

- programmers-guide/chapters/I.md
Remove duplicate plugin list. Add overview instructions for Cocos, Installer and bundles.
> Update Appendix I. 

- manual/framework/cocos2d-js/index.md
- manual/framework/cocos2d-js/meta.json
- manual/framework/html5/index.md
- manual/framework/html5/meta.json
- utils/build-doc.js
- utils/layout-github/page.html
Add JS docs and API reference for unified cocos.com docs.
> Add JS docs and API reference for unified cocos.com docs

- manual/framework/html5/v2/cocos-console/zh.md
> Fixed format issues.

- editors_and_tools/cocosCLTool.md
- installation/Tizen.md
BTW, remove the document of command `cocos gen-templates`.
> Update the tizen related document for the cocos command support.

- build.sh
- programmers-guide/other_node_types.md
- programmers-guide/ui_components.md
> fix build issues
